@startuml
title __JAVA's Class Diagram__\n


    class Main {
        ~ driver : WebDriver
        + Main()
        {static} + main()
    }



    class SearchAndAddToCart {
        + cart()
        + search()
    }


@enduml